package pkg;

import javax.swing.JButton;

/**
 *
 * @author Me
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainMenu() {
        initComponents();
        makeTransparentBtn(btnClassic);
        makeTransparentBtn(btnImhotep);
        makeTransparentBtn(btnDynasty);
        makeTransparentBtn(btnQuit);
    }

    private static void makeTransparentBtn(JButton jButton) {
        jButton.setOpaque(false);
        jButton.setContentAreaFilled(false);
        jButton.setBorderPainted(false);
    }

    private void setup(Piece[][] selectedBoard) {
        Board.board = selectedBoard;
        new Board().setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClassic = new javax.swing.JButton();
        btnImhotep = new javax.swing.JButton();
        btnDynasty = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClassic.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnClassic.setForeground(new java.awt.Color(255, 255, 255));
        btnClassic.setText("Classic");
        btnClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassicActionPerformed(evt);
            }
        });
        getContentPane().add(btnClassic);
        btnClassic.setBounds(10, 6, 380, 39);

        btnImhotep.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnImhotep.setForeground(new java.awt.Color(255, 255, 255));
        btnImhotep.setText("Imhotep");
        btnImhotep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImhotepActionPerformed(evt);
            }
        });
        getContentPane().add(btnImhotep);
        btnImhotep.setBounds(10, 51, 380, 39);

        btnDynasty.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnDynasty.setForeground(new java.awt.Color(255, 255, 255));
        btnDynasty.setText("Dynasty");
        btnDynasty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDynastyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDynasty);
        btnDynasty.setBounds(10, 96, 380, 39);

        btnQuit.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(10, 153, 380, 39);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egyptian-hieroglyphics.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 410, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassicActionPerformed
        setup(Board.CLASSIC);
    }//GEN-LAST:event_btnClassicActionPerformed

    private void btnImhotepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImhotepActionPerformed
        setup(Board.IMHOTEP);
    }//GEN-LAST:event_btnImhotepActionPerformed

    private void btnDynastyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDynastyActionPerformed
        setup(Board.DYNASTY);
    }//GEN-LAST:event_btnDynastyActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassic;
    private javax.swing.JButton btnDynasty;
    private javax.swing.JButton btnImhotep;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
